---
- name: Download the artifact
  maven_artifact:
    group_id: in.shan5a6
    artifact_id: myweb
    repository_url: 'http://35.92.15.103/repository/app1-artifacts'
    extension: war
    version: "{{ artifact_version }}"
    username: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    dest: /opt/tomcat/webapps/

- name: Restart tomcat
  systemd:
    name: tomcat-service
    state: restarted  
